version: 1.0.{build}
image: Visual Studio 2022
build_script:
- ps: .\build_nuget.ps1
artifacts:
- path: Output\*.nupkg
  name: NugetPackages
deploy:
- provider: NuGet
  api_key:
    secure: /NhBMvN+VcLzO/DK4bGHCn7lEgsIOyNM7Th3vkFzHrbwmQyXJdheB3qMx1ymlycF
  username:
    secure: 1K8aMtHh4cgJD51abewigQ==
  artifact: NugetPackages